server:
  port: 18080
  servlet:
    context-path: /pdgjTest

#读取log配置文件
logging:
  config: classpath:logback-boot.xml
#日志路径
  log_root: "E:/njdk/pdfjTest/"

spring :
  datasource :
    url : jdbc:mysql://180.169.154.251:23306/pggjtest?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
    #第一次启动做建表用，之后注释掉
    initialization-mode: always
mybatis :
  config-location : classpath:/mybatis-config.xml
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "

